version: "2.1"
services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"

  elon:
    depends_on: 
      - rabbitmq
    
    build: ./PlayersWebApp/
    environment:
      - RabbitMQ:host=rabbitmq
      - PLAYER=Elon
    
    ports:
      - "5031:80"
        
  mark:
    depends_on:
      - rabbitmq

    build: ./PlayersWebApp/
    environment:
      - RabbitMQ:host=rabbitmq
      - PLAYER=Mark

    ports:
      - "5032:80"      
    
